pipeline:

  pushTag:
    image: docker
    commands:
      - echo "Push Tag"

  push:
    image: docker
    commands:
      - echo "Push"
    when:
      event: push

  notify:
    image: plugins/slack
    channel: adam-test
    username: drone
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
