pipeline:

  pushTag:
    image: docker
    commands:
      - echo "Push Tag"

  push:
    image: docker
    commands:
      - echo "Push"
    when:
      event: push

  deploy:
    image: microadam/drone-navy
    appId: lei-site
    order: deploy
    version: "${DRONE_TAG##v}"
    secrets: [ admiral_url, admiral_username, admiral_password ]

  notify:
    image: plugins/slack
    channel: adam-test
    username: drone
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
