pipeline:

  pushTag:
    image: docker
    commands:
      - echo "Push Tag"

  push:
    image: docker
    commands:
      - echo "Push"
    when:
      event: push

  deploy:
    image: microadam/drone-navy
    pull: true
    appId: lei-site-test
    order: deploy
    version: "1.0.0-0"
    secrets: [ admiral_host ]

  notify:
    image: plugins/slack
    channel: adam-test
    username: drone
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
